<a href="https://colab.research.google.com/github/rohithjagan/Machine-Learning-Task/blob/main/Machine_Learning_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# TASK 1: DATA PREPARATION

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Telco_Customer_Churn_Dataset.csv to Telco_Customer_Churn_Dataset (1).csv

In [ ]:
df = pd.read_csv(list(uploaded.keys())[0])
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
print(df.isnull().sum())
df = df.dropna()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
le = LabelEncoder()

for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = le.fit_transform(df[column])

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,5375,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,2,29.85,2505,0
1,3962,1,0,0,0,34,1,0,0,2,...,2,0,0,0,1,0,3,56.95,1466,0
2,2564,1,0,0,0,2,1,0,0,2,...,0,0,0,0,0,1,3,53.85,157,1
3,5535,1,0,0,0,45,0,1,0,2,...,2,2,0,0,1,0,0,42.30,1400,0
4,6511,0,0,0,0,2,1,0,1,0,...,0,0,0,0,0,1,2,70.70,925,1

In [ ]:
X = df.drop('Churn', axis=1)
y = df['Churn']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y)

X_train.shape, X_test.shape

((5634, 20), (1409, 20))

In [ ]:
selector = SelectKBest(score_func=chi2, k=10)
selector.fit(X, y)

scores = pd.DataFrame({
    'Feature': X.columns,
    'Score': selector.scores_
}).sort_values(by='Score', ascending=False)

scores

             Feature         Score
5             tenure  16278.923685
18    MonthlyCharges   3680.787699
0         customerID   2516.968803
19      TotalCharges   1616.483021
15          Contract   1115.780167
9     OnlineSecurity    551.611529
12       TechSupport    523.303866
10      OnlineBackup    230.086520
11  DeviceProtection    191.303140
2      SeniorCitizen    134.351545
4         Dependents    133.036443
16  PaperlessBilling    105.680863
3            Partner     82.412083
17     PaymentMethod     58.492250
8    InternetService      9.821028
7      MultipleLines      9.746921
14   StreamingMovies      8.235399
13       StreamingTV      7.490203
1             gender      0.258699
6       PhoneService      0.097261

In [ ]:
selected_features = scores['Feature'].values[:10]
selected_features

array(['tenure', 'MonthlyCharges', 'customerID', 'TotalCharges',
       'Contract', 'OnlineSecurity', 'TechSupport', 'OnlineBackup',
       'DeviceProtection', 'SeniorCitizen'], dtype=object)

In [ ]:
X_train_sel = X_train[selected_features]
X_test_sel = X_test[selected_features]

In [ ]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier()
}

In [ ]:
trained_models = {}

for name, model in models.items():
    model.fit(X_train_sel, y_train)
    trained_models[name] = model
    print(f"{name} trained successfully!")

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression trained successfully!
Random Forest trained successfully!
Gradient Boosting trained successfully!

In [ ]:
for name, model in trained_models.items():
    y_pred = model.predict(X_test_sel)

    print("\n============================")
    print(f" Model: {name}")
    print("============================")

    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall:", recall_score(y_test, y_pred))
    print("F1 Score:", f1_score(y_test, y_pred))
    print("ROC-AUC:", roc_auc_score(y_test, y_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

============================
 Model: Logistic Regression
============================
Accuracy: 0.7821149751596878
Precision: 0.6091205211726385
Recall: 0.5
F1 Score: 0.5491923641703378
ROC-AUC: 0.6920289855072465

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.88      0.86      1035
           1       0.61      0.50      0.55       374

    accuracy                           0.78      1409
   macro avg       0.72      0.69      0.70      1409
weighted avg       0.77      0.78      0.77      1409


============================
 Model: Random Forest
============================
Accuracy: 0.7750177430801988
Precision: 0.5953177257525084
Recall: 0.47593582887700536
F1 Score: 0.5289747399702823
ROC-AUC: 0.6795138081583096

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.88      0.85      1035
           1       0.60      0.48      0.53       374

    accuracy                           0.78      1409
   macro avg       0.71      0.68      0.69      1409
weighted avg       0.76      0.78      0.77      1409


============================
 Model: Gradient Boosting
============================
Accuracy: 0.7913413768630234
Precision: 0.6428571428571429
Recall: 0.48128342245989303
F1 Score: 0.5504587155963303
ROC-AUC: 0.6923325324859851

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1035
           1       0.64      0.48      0.55       374

    accuracy                           0.79      1409
   macro avg       0.74      0.69      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [ ]:
results = []

for name, model in trained_models.items():
    y_pred = model.predict(X_test_sel)
    results.append([
        name,
        accuracy_score(y_test, y_pred),
        precision_score(y_test, y_pred),
        recall_score(y_test, y_pred),
        f1_score(y_test, y_pred),
        roc_auc_score(y_test, y_pred)
    ])

results_df = pd.DataFrame(results, columns=["Model", "Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"])
results_df

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0  Logistic Regression  0.782115   0.609121  0.500000  0.549192  0.692029
1        Random Forest  0.775018   0.595318  0.475936  0.528975  0.679514
2    Gradient Boosting  0.791341   0.642857  0.481283  0.550459  0.692333